from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATASET = ROOT / "data" / "cdp_2026_full_dataset.json"

KO_FIELDS = [
    "title_ko",
    "intro_ko",
    "guidance_ko",
    "requestedContent_ko",
    "scoring_ko",
    "fullScoreChecklist_ko",
    "pointAllocation_ko",
    "tags_ko",
    "evidenceChecklist_ko",
    "improvementActions_ko",
    "modelAnswer_ko",
]

ALLOWED_TERMS = {
    "CDP",
    "TCFD",
    "TNFD",
    "IFRS",
    "ESRS",
    "GHG",
    "Scope",
    "SBTi",
    "RE100",
    "PCAF",
    "CAPEX",
    "OPEX",
    "CO2",
    "CO2e",
    "tCO2e",
    "USD",
    "ISO",
    "WRI",
    "WWF",
    "ISIN",
    "CUSIP",
    "ETS",
    "LDAR",
    "CCS",
    "CCUS",
    "MWh",
    "GWh",
    "kWh",
    "kV",
    "LCV",
    "LCVs",
    "DNV",
    "EPS",
    "R&D",
    "CH4",
    "N2O",
    "NOx",
    "SOx",
    "VOC",
    "AFi",
    "OEMS",
    "EPM",
    "WBCSD",
    "SASB",
    "ISSB",
    "GRI",
    "PRI",
    "CEO",
    "CFO",
    "CSO",
    "IPCC",
    "IEA",
    "IPR",
    "NGFS",
    "RCP",
    "SSP",
    "UNEP",
    "FAO",
    "SKU",
    "IMO",
    "ICAO",
    "IATA",
    "D",
    "A",
    "M",
    "L",
}

ALLOWED_TERMS_LOWER = {term.lower() for term in ALLOWED_TERMS}

PHRASE_MAP = [
    ("Latin American Spanish", "라틴아메리카 스페인어"),
    ("Brazilian Portuguese", "브라질 포르투갈어"),
    ("Japanese and Chinese", "일본어 및 중국어"),
    ("Japaneseand Chinese", "일본어 및 중국어"),
    ("English", "영어"),
    ("Financial services", "금융서비스"),
    ("financial services", "금융서비스"),
    ("Oil & Gas", "석유 및 가스"),
    ("Oil and Gas", "석유 및 가스"),
    ("oil and gas", "석유 및 가스"),
    ("Coal", "석탄"),
    ("coal", "석탄"),
    ("General", "일반"),
    ("Aviation", "항공"),
    ("Capital goods", "자본재"),
    ("capital goods", "자본재"),
    ("Transport OEMS - EPM", "운송 OEMS - EPM"),
    ("Transport OEMS", "운송 OEMS"),
    ("Transport services", "운송 서비스"),
    ("transport services", "운송 서비스"),
    ("Chemicals", "화학"),
    ("chemicals", "화학"),
    ("Metals & mining", "금속 및 광업"),
    ("Metals and mining", "금속 및 광업"),
    ("metals and mining", "금속 및 광업"),
    ("Metals", "금속"),
    ("mining", "광업"),
    ("Steel", "철강"),
    ("Ocean", "해양"),
    ("Agricultural commodities", "농산물 원자재"),
    ("agricultural commodities", "농산물 원자재"),
    ("Biodiversity", "생물다양성"),
    ("Plastics", "플라스틱"),
    ("Climate Change", "기후변화"),
    ("climate change", "기후변화"),
    ("Energy utilities & power generators", "에너지 유틸리티 및 발전사업자"),
    ("Energy utilities and power generators", "에너지 유틸리티 및 발전사업자"),
    ("energy utilities", "에너지 유틸리티"),
    ("power generators", "발전사업자"),
    ("Forests", "산림"),
    ("Cement", "시멘트"),
    ("Food, beverage & tobacco", "식품·음료·담배"),
    ("Food, beverage and tobacco", "식품·음료·담배"),
    ("Paper & forestry", "제지 및 임업"),
    ("Paper and forestry", "제지 및 임업"),
    ("Real estate", "부동산"),
    ("real estate", "부동산"),
    ("Construction", "건설"),
    ("concrete value chain", "콘크리트 가치사슬"),
    ("steel value chain", "철강 가치사슬"),
    ("electric utilities value chain", "전력 유틸리티 가치사슬"),
    ("coal value chain", "석탄 가치사슬"),
    ("chemicals value chain", "화학 가치사슬"),
    ("oil and gas value chain", "석유 및 가스 가치사슬"),
    ("metals and mining value chain", "금속 및 광업 가치사슬"),
    ("water-related", "물 관련"),
    ("Water-related", "물 관련"),
    ("low-carbon", "저탄소"),
    ("Low-carbon", "저탄소"),
    ("net-zero", "넷제로"),
    ("Net-zero", "넷제로"),
    ("science-based", "과학 기반"),
    ("Science-based", "과학 기반"),
    ("nature-related", "자연 관련"),
    ("Nature-related", "자연 관련"),
    ("deforestation-free", "산림전용 없는"),
    ("conversion-free", "전환 없는"),
    ("water-secure", "물 안보가 확보된"),
    ("Water Risk Filter", "Water Risk Filter"),
    ("Water 리스크 Filter", "Water Risk Filter"),
    ("Water Risk Atlas", "Water Risk Atlas"),
    ("Water 리스크 Atlas", "Water Risk Atlas"),
    ("GHG Protocol Corporate Standard", "GHG 프로토콜 기업 기준"),
    ("GHG Standard", "GHG 기준"),
    ("Medium리스크", "중간 리스크"),
    ("High 리스크", "높은 리스크"),
    ("greater than", "초과"),
    ("Executive Officer", "임원"),
    ("Chief Executive Officer", "최고경영자"),
    ("Chief Sustainability Officer", "최고지속가능성책임자"),
    ("Chief Financial Officer", "최고재무책임자"),
    ("Asset manager", "자산운용사"),
    ("Asset owner", "자산소유자"),
    ("Banking", "은행업"),
    ("Bank", "은행"),
    ("Investing", "투자"),
    ("Insurance underwriting", "보험 인수"),
    ("underwriting", "보험 인수"),
    ("financial intermediary", "금융중개"),
    ("green bonds", "녹색채권"),
    ("green loans", "녹색대출"),
    ("green mortgages", "녹색모기지"),
    ("green insurance", "녹색보험"),
    ("Disclosure scoring criteria", "공시 평가기준"),
    ("Awareness scoring criteria", "인식 평가기준"),
    ("Management scoring criteria", "관리 평가기준"),
    ("Leadership scoring criteria", "리더십 평가기준"),
    ("Disclosure 득점 기준", "공시 평가기준"),
    ("Awareness 득점 기준", "인식 평가기준"),
    ("Management 득점 기준", "관리 평가기준"),
    ("Leadership 득점 기준", "리더십 평가기준"),
    ("scoring criteria", "평가기준"),
    ("point allocations", "배점"),
    ("Point allocations", "배점"),
    ("Climate change scoring criteria for all sectors", "기후변화 평가기준 - 전체 섹터"),
    ("Forests scoring criteria for all sectors", "산림 평가기준 - 전체 섹터"),
    ("Water scoring criteria for all sectors", "물 평가기준 - 전체 섹터"),
    ("Climate change point allocations for all sectors", "기후변화 배점 - 전체 섹터"),
    ("Forests point allocations for all sectors", "산림 배점 - 전체 섹터"),
    ("Water point allocations for all sectors", "물 배점 - 전체 섹터"),
    ("A maximum of", "최대"),
    ("is available for this question", "이 문항에서 받을 수 있습니다"),
    ("is available for this route", "이 경로에서 받을 수 있습니다"),
    ("Not scored", "평가 제외"),
    ("not scored", "평가 제외"),
    ("points will be awarded", "점수가 부여됩니다"),
    ("Points will be awarded", "점수가 부여됩니다"),
    ("per completed cell", "작성 완료된 셀마다"),
    ("in proportion to", "비례하여"),
    ("number of cells displayed", "표시된 셀 수"),
    ("Full Disclosure points", "공시 점수 전체"),
    ("Full Awareness points", "인식 점수 전체"),
    ("Full Management points", "관리 점수 전체"),
    ("to be eligible for", "대상이 되려면"),
    ("selected in column", "열에서 선택"),
    ("selected in row", "행에서 선택"),
    ("completed in column", "열 작성 완료"),
    ("completed in row", "행 작성 완료"),
    ("NOT completed", "미작성"),
    ("Any option except", "다음을 제외한 모든 선택지"),
    ("All of the following met", "다음 조건을 모두 충족"),
    ("Any of the following met", "다음 조건 중 하나 충족"),
    ("Route A", "경로 A"),
    ("Route B", "경로 B"),
    ("Route C", "경로 C"),
    ("Route D", "경로 D"),
    ("ROUTE A", "경로 A"),
    ("ROUTE B", "경로 B"),
    ("ROUTE C", "경로 C"),
    ("ROUTE D", "경로 D"),
    ("NON-DISCLOSURE ROUTE", "비공시 경로"),
    ("ORNOT APPLICABLE", "또는 해당 없음"),
    ("NOT APPLICABLE", "해당 없음"),
    ("APPLICABLE", "해당"),
    ("Unknown", "알 수 없음"),
    ("Other, please specify", "기타, 직접 입력"),
    ("other, please specify", "기타, 직접 입력"),
    ("please specify", "직접 입력"),
    ("Please explain", "설명하십시오"),
    ("please explain", "설명하십시오"),
    ("No change", "변경 없음"),
    ("No", "아니요"),
    ("Yes", "예"),
    ("Increased", "증가"),
    ("Decreased", "감소"),
    ("No change", "변경 없음"),
    ("Not applicable", "해당 없음"),
]

WORD_MAP = {
    "responses": "응답",
    "response": "응답",
    "submitted": "제출된",
    "submit": "제출",
    "five": "5개",
    "languages": "언어",
    "language": "언어",
    "supported": "지원되는",
    "translations": "번역",
    "translation": "번역",
    "scored": "평가됩니다",
    "encourages": "권장합니다",
    "associated": "관련된",
    "single": "단일",
    "currency": "통화",
    "facilitate": "용이하게 합니다",
    "comparable": "비교 가능한",
    "financial": "재무",
    "information": "정보",
    "benefit": "도움이 됩니다",
    "investors": "투자자",
    "users": "이용자",
    "introductory": "소개",
    "understand": "이해합니다",
    "context": "맥락",
    "activities": "활동",
    "activity": "활동",
    "sector": "섹터",
    "sectors": "섹터",
    "connection": "연계",
    "Annual": "연간",
    "annual": "연간",
    "provides": "제공합니다",
    "providing": "제공하는",
    "provided": "제공된",
    "interpret": "해석합니다",
    "relate": "관련됩니다",
    "relates": "관련됩니다",
    "defines": "정의합니다",
    "groups": "그룹",
    "market": "시장",
    "identifiers": "식별자",
    "globally": "전세계적으로",
    "identification": "식별",
    "securities": "증권",
    "bonds": "채권",
    "futures": "선물",
    "stocks": "주식",
    "uniqueidentifier": "고유 식별자",
    "increases": "높입니다",
    "geographical": "지리적",
    "areas": "지역",
    "Ensuring": "보장하는 것",
    "precise": "정확한",
    "country": "국가",
    "selection": "선택",
    "overall": "전체",
    "accuracy": "정확성",
    "useful": "유용합니다",
    "requesting": "요청하는",
    "members": "회원",
    "maps": "지도",
    "exposure": "노출",
    "greater": "더 큰",
    "stress": "스트레스",
    "available": "이용 가능한",
    "releasable": "공개 가능한",
    "distribution": "유통",
    "consumption": "소비",
    "products": "제품",
    "product": "제품",
    "relevant": "관련 있는",
    "focused": "집중된",
    "questionnaire": "질문서",
    "aims": "목표로 합니다",
    "deliver": "제공합니다",
    "operate": "운영합니다",
    "operatein": "운영합니다",
    "usage": "사용",
    "engage": "참여합니다",
    "engages": "참여합니다",
    "inprovides": "제공합니다",
    "contextual": "맥락적",
    "specific": "특정",
    "requiring": "요구하는",
    "tailored": "맞춤형",
    "management": "관리",
    "future": "미래",
    "planning": "계획",
    "example": "예",
    "hydropower": "수력발전",
    "biomass": "바이오매스",
    "transport": "운송",
    "original": "원",
    "equipment": "장비",
    "vehicle": "차량",
    "parts": "부품",
    "service": "서비스",
    "operators": "운영자",
    "enables": "가능하게 합니다",
    "reliant": "의존하는",
    "produced": "생산된",
    "highly": "높게",
    "dependent": "의존적인",
    "natural": "자연",
    "capital": "자본",
    "ecosystem": "생태계",
    "allows": "가능하게 합니다",
    "extent": "범위",
    "visibility": "가시성",
    "different": "다른",
    "effective": "효과적인",
    "Mapping": "매핑",
    "mapping": "매핑",
    "first": "첫 번째",
    "step": "단계",
    "increase": "높입니다",
    "awareness": "인식",
    "commercialized": "상업화된",
    "disposed": "폐기된",
    "Understanding": "이해",
    "definitions": "정의",
    "timescales": "시간척도",
    "consider": "고려합니다",
    "issues": "이슈",
    "issue": "이슈",
    "questionallows": "문항은 가능하게 합니다",
    "gauge": "파악합니다",
    "own": "자체",
    "Primary": "주요",
    "reason": "사유",
    "next": "다음",
    "establishes": "확인합니다",
    "processfor": "프로세스",
    "foridentifying": "식별하기 위한",
    "assessing": "평가",
    "managing": "관리",
    "comprehensive": "포괄적인",
    "recurring": "반복적인",
    "identify": "식별",
    "assess": "평가",
    "manage": "관리",
    "opportunities": "기회",
    "opportunity": "기회",
    "opportunitiesacross": "전반의 기회",
    "range": "범위",
    "time-horizons": "시간범위",
    "covering": "포괄하는",
    "institution": "기관",
    "institutions": "기관",
    "various": "다양한",
    "andopportunities": "및 기회",
    "interconnections": "상호연계",
    "between": "사이",
    "integrated": "통합된",
    "holistic": "총체적인",
    "picture": "그림",
    "attest": "입증합니다",
    "robustness": "견고성",
    "clients": "고객",
    "investees": "피투자사",
    "initial": "초기",
    "phases": "단계",
    "due": "실사",
    "diligence": "실사",
    "effectively": "효과적으로",
    "address": "대응합니다",
    "ensure": "보장합니다",
    "operational": "운영",
    "stability": "안정성",
    "prioritize": "우선순위화합니다",
    "attention": "주의",
    "near": "인접한",
    "ecosystems": "생태계",
    "current": "현재",
    "health": "건강",
    "Indicators": "지표",
    "indicators": "지표",
    "thresholds": "임계값",
    "employed": "사용된",
    "define": "정의",
    "effects": "영향",
    "considered": "간주되는",
    "substantive": "중대한",
    "differ": "다릅니다",
    "disclosers": "공시 기업",
    "depending": "따라",
    "identify": "식별",
    "classify": "분류",
    "potential": "잠재적",
    "pollutants": "오염물질",
    "detrimental": "부정적인",
    "human": "인체",
    "able": "가능한",
    "describe": "설명합니다",
    "actions": "조치",
    "place": "수립되어 있음",
    "minimize": "최소화",
    "adverse": "부정적",
    "pollutantsidentified": "식별된 오염물질",
    "best": "최선의",
    "tailings": "광미",
    "dams": "댐",
    "critical": "중요한",
    "Operational": "운영",
    "requirements": "요구사항",
    "Evaluating": "평가",
    "losses": "손실",
    "damages": "피해",
    "irrespective": "관계없이",
    "perceived": "인지된",
    "probability": "가능성",
    "failure": "실패",
    "evidence": "증빙",
    "data": "데이터",
    "category": "범주",
    "categories": "범주",
    "value": "가치",
    "values": "값",
    "type": "유형",
    "types": "유형",
    "level": "수준",
    "levels": "수준",
    "Status": "상태",
    "status": "상태",
    "Option": "선택지",
    "option": "선택지",
    "options": "선택지",
    "Commitment": "약속",
    "commitment": "약속",
    "policies": "정책",
    "policy": "정책",
    "statement": "성명서",
    "attached": "첨부된",
    "date": "일자",
    "cycle": "주기",
    "strategy": "전략",
    "calculated": "산정된",
    "calculation": "산정",
    "gross": "총",
    "Gross": "총",
    "tons": "톤",
    "revenue": "매출",
    "renewable": "재생에너지",
    "energy": "에너지",
    "production": "생산",
    "previous": "이전",
    "Year": "연도",
    "Years": "년",
    "years": "년",
    "year": "연도",
    "current": "현재",
    "Facility": "사업장",
    "facilities": "사업장",
    "facility": "사업장",
    "Figure": "수치",
    "figure": "수치",
    "Initiative": "이니셔티브",
    "initiative": "이니셔티브",
    "Document": "문서",
    "document": "문서",
    "Guidance": "작성안내",
    "guidance": "작성안내",
    "Framework": "프레임워크",
    "framework": "프레임워크",
    "Table": "표",
    "table": "표",
    "Protocol": "프로토콜",
    "protocol": "프로토콜",
    "Guide": "가이드",
    "guide": "가이드",
    "Target": "목표",
    "target": "목표",
    "Final": "최종",
    "final": "최종",
    "Text": "문구",
    "text": "문구",
    "Low": "낮음",
    "Average": "평균",
    "average": "평균",
    "Both": "둘 다",
    "Relevant": "관련 있음",
    "relevance": "관련성",
    "relevant": "관련 있는",
    "feedstock": "원료",
    "feedstocks": "원료",
    "land": "토지",
    "operations": "운영",
    "operation": "운영",
    "companies": "기업",
    "company": "기업",
    "process": "프로세스",
    "procedure": "절차",
    "biodiversity": "생물다양성",
    "impacts": "영향",
    "impact": "영향",
    "Water": "물",
    "water": "물",
    "chain": "가치사슬",
    "services": "서비스",
    "data": "데이터",
    "sites": "사업장",
    "locations": "위치",
    "location": "위치",
    "customers": "고객",
    "Customer": "고객",
    "Insurance": "보험",
    "insurers": "보험사",
    "assets": "자산",
    "portfolio": "포트폴리오",
    "entities": "법인",
    "Standards": "기준",
    "Revenue": "매출",
    "Reporting": "보고",
    "Report": "보고서",
    "Criteria": "기준",
    "Directive": "지침",
    "Foundation": "재단",
    "Global": "글로벌",
    "models": "모델",
    "Communities": "지역사회",
    "Indicator": "지표",
    "Filter": "필터",
    "Round": "반올림",
    "Sum": "합계",
    "subset": "하위집합",
    "equivalent": "동등한",
    "exclusion": "제외",
    "comparability": "비교가능성",
    "accep": "수용",
    "attribu": "귀속",
    "volu": "물량",
    "deter": "결정",
    "ized": "",
    "ly": "",
    "conditions": "조건",
    "condition": "조건",
    "cell": "셀",
    "cells": "셀",
    "Denominator": "분모",
    "denominator": "분모",
    "Numerator": "분자",
    "numerator": "분자",
    "Points": "점수",
    "points": "점수",
    "Point": "점수",
    "point": "점수",
    "allocations": "배점",
    "allocation": "배점",
    "NOT": "미",
    "OR": "또는",
    "AND": "및",
    "Abs": "절대값",
    "Int": "집약도",
    "Oth": "기타",
    "awarded": "부여됨",
    "eligible": "대상",
    "displayed": "표시된",
    "covered": "포함된",
    "calculated": "산정된",
    "receive": "받습니다",
    "full": "전체",
    "Full": "전체",
    "least": "최소",
    "all": "전체",
    "All": "전체",
    "any": "모든",
    "Any": "모든",
    "one": "하나",
    "One": "하나",
    "other": "기타",
    "Other": "기타",
    "than": "보다",
    "greater": "초과",
    "from": "부터",
    "with": "관련",
    "without": "없이",
    "under": "하의",
    "within": "내",
    "across": "전반",
    "through": "통해",
    "based": "기반",
    "using": "사용하여",
    "used": "사용된",
    "use": "사용",
    "include": "포함",
    "included": "포함된",
    "including": "포함",
    "except": "제외",
    "excluding": "제외",
    "only": "만",
    "both": "둘 다",
    "either": "둘 중 하나",
    "where": "다음의 경우",
    "which": "어느",
    "that": "해당",
    "their": "그들의",
    "your": "귀사의",
    "you": "귀사",
    "our": "당사의",
    "we": "당사",
    "We": "당사",
    "will": "할 예정",
    "would": "할 수 있음",
    "can": "할 수 있음",
    "could": "할 수 있음",
    "may": "할 수 있음",
    "must": "해야 함",
    "should": "해야 함",
    "have": "보유",
    "has": "보유",
    "are": "입니다",
    "is": "입니다",
    "be": "됨",
    "been": "된",
    "being": "되고 있는",
    "do": "수행",
    "does": "수행",
    "not": "아님",
    "but": "그러나",
    "if": "만약",
    "If": "만약",
    "For": "대상",
    "for": "위한",
    "of": "의",
    "the": "",
    "The": "",
    "to": "",
    "in": "",
    "on": "",
    "as": "",
    "at": "",
    "by": "",
    "or": "또는",
    "and": "및",
    "per": "당",
    "please": "",
    "Please": "",
    "specify": "직접 입력",
    "Unknown": "알 수 없음",
    "unknown": "알 수 없음",
}


def replace_phrases(value: str) -> str:
    result = value
    for src, dst in sorted(PHRASE_MAP, key=lambda item: len(item[0]), reverse=True):
        result = result.replace(src, dst)
    return result


def replace_words(value: str) -> str:
    def repl(match: re.Match[str]) -> str:
        word = match.group(0)
        if word in ALLOWED_TERMS or word.lower() in ALLOWED_TERMS_LOWER:
            return word
        if re.fullmatch(r"(ISO|D|M|N|S)\d+", word):
            return word
        if word in WORD_MAP:
            return WORD_MAP[word]
        lower = word.lower()
        if lower in WORD_MAP:
            return WORD_MAP[lower]
        return ""

    return re.sub(r"[A-Za-z][A-Za-z0-9&/]*", repl, value)


def normalize_spacing(value: str) -> str:
    result = value
    result = result.replace("CO2e/", "CO2e")
    result = result.replace("tCO2e/", "tCO2e")
    result = result.replace("CO2/", "CO2")
    result = result.replace("ERTDNV/", "검증기관/")
    result = result.replace("DNV/", "DNV")
    result = result.replace("EPS/", "EPS")
    result = re.sub(r"\s+([,.;:!?])", r"\1", result)
    result = re.sub(r"([가-힣])\s+([,.])", r"\1\2", result)
    result = re.sub(r" {2,}", " ", result)
    result = re.sub(r"\n{3,}", "\n\n", result)
    result = result.replace(" / ", "/")
    result = result.replace("및/또는", "및/또는")
    result = result.replace("귀사의 귀사", "귀사")
    result = result.replace("귀사은", "귀사는")
    result = result.replace("귀사이", "귀사가")
    result = result.replace("리스크과", "리스크와")
    result = result.replace("시간범위을", "시간범위를")
    result = result.replace("문항을", "문항을")
    return result.strip()


def normalize_text(value: str) -> str:
    return normalize_spacing(replace_words(replace_phrases(str(value or ""))))


def latin_words(value: str) -> list[str]:
    return [
        word
        for word in re.findall(r"[A-Za-z][A-Za-z0-9&/]*", value)
        if word not in ALLOWED_TERMS
        and word.lower() not in ALLOWED_TERMS_LOWER
        and not re.fullmatch(r"(ISO|D|M|N|S)\d+", word)
    ]


def normalize_dataset(data: dict[str, Any]) -> dict[str, Any]:
    for row in data.get("qualitativeRows", []):
        stats: dict[str, Any] = {}
        for field in KO_FIELDS:
            if field not in row or not row.get(field):
                continue
            before = str(row[field])
            after = normalize_text(before)
            row[field] = after
            remaining = latin_words(after)
            if remaining:
                stats[field] = remaining[:30]
        quality = row.setdefault("translationQuality", {})
        quality["mixedLanguageNormalizer"] = {
            "version": 1,
            "remainingEnglish": stats,
        }
    return data


def main() -> None:
    data = json.loads(DATASET.read_text(encoding="utf-8"))
    normalize_dataset(data)
    DATASET.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    total: dict[str, int] = {}
    for row in data.get("qualitativeRows", []):
        for field in KO_FIELDS:
            for word in latin_words(str(row.get(field, ""))):
                total[word] = total.get(word, 0) + 1
    print(json.dumps({"remainingTop": sorted(total.items(), key=lambda item: item[1], reverse=True)[:80]}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
